#include "tiles.h"

#include <string.h>

static const TileDefinition g_tile_definitions[TILE_ID_COUNT] =
{
    {
        .id = TILE_GRASS,
        .name = "Grass",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_DRYGRASS,
        .name = "DryGrass",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_TALLGRASS,
        .name = "TallGrass",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_DIRT,
        .name = "Dirt",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_PACKEDDIRT,
        .name = "PackedDirt",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_MUD,
        .name = "Mud",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_SAND,
        .name = "Sand",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_DESERTSAND,
        .name = "DesertSand",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_GRAVEL,
        .name = "Gravel",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_CLAY,
        .name = "Clay",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_MOSS,
        .name = "Moss",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_FORESTFLOOR,
        .name = "ForestFloor",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_SNOW,
        .name = "Snow",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_ICE,
        .name = "Ice",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_FROZENGROUND,
        .name = "FrozenGround",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_PERMAFROST,
        .name = "Permafrost",
        .walkable = true,
        .layer = TILE_LAYER_UNKNOWN,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_BASALT,
        .name = "Basalt",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_GRANITE,
        .name = "Granite",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_LIMESTONE,
        .name = "Limestone",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_WETSOIL,
        .name = "WetSoil",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_FLOODEDGROUND,
        .name = "FloodedGround",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_SHALLOWWATER,
        .name = "ShallowWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "Water",
        .resource_yield = 3,
        .renewable = true,
    },
    {
        .id = TILE_DEEPWATER,
        .name = "DeepWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "Water",
        .resource_yield = 4,
        .renewable = true,
    },
    {
        .id = TILE_OCEANWATER,
        .name = "OceanWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "SaltWater",
        .resource_yield = 4,
        .renewable = true,
    },
    {
        .id = TILE_RIVERWATER,
        .name = "RiverWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "Water",
        .resource_yield = 4,
        .renewable = true,
    },
    {
        .id = TILE_STREAMWATER,
        .name = "StreamWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "Water",
        .resource_yield = 2,
        .renewable = true,
    },
    {
        .id = TILE_SWAMPWATER,
        .name = "SwampWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "Water",
        .resource_yield = 2,
        .renewable = true,
    },
    {
        .id = TILE_MARSHWATER,
        .name = "MarshWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "Water",
        .resource_yield = 2,
        .renewable = true,
    },
    {
        .id = TILE_PONDWATER,
        .name = "PondWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "Water",
        .resource_yield = 3,
        .renewable = true,
    },
    {
        .id = TILE_LAKEWATER,
        .name = "LakeWater",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
        .primary_resource = "Water",
        .resource_yield = 4,
        .renewable = true,
    },
    {
        .id = TILE_WATERFOAM,
        .name = "WaterFoam",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_WATERCURRENT,
        .name = "WaterCurrent",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_WATERFALL,
        .name = "Waterfall",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_WATEREDGE,
        .name = "WaterEdge",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_TOXIC_WATER,
        .name = "Toxic Water",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = false,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_OILSPILL,
        .name = "OilSpill",
        .walkable = true,
        .layer = TILE_LAYER_UNKNOWN,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 2,
    },
    {
        .id = TILE_LAVA,
        .name = "Lava",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_MAGMA,
        .name = "Magma",
        .walkable = false,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = true,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_TREEOAK,
        .name = "TreeOak",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Wood",
        .resource_yield = 8,
        .renewable = true,
    },
    {
        .id = TILE_TREEPINE,
        .name = "TreePine",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Wood",
        .resource_yield = 9,
        .renewable = true,
    },
    {
        .id = TILE_TREEBIRCH,
        .name = "TreeBirch",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Wood",
        .resource_yield = 7,
        .renewable = true,
    },
    {
        .id = TILE_TREEPALM,
        .name = "TreePalm",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Wood",
        .resource_yield = 6,
        .renewable = true,
    },
    {
        .id = TILE_TREEDEAD,
        .name = "TreeDead",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Wood",
        .resource_yield = 5,
        .renewable = false,
    },
    {
        .id = TILE_TREEBURNT,
        .name = "TreeBurnt",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Charcoal",
        .resource_yield = 4,
        .renewable = false,
    },
    {
        .id = TILE_TREESAPLING,
        .name = "TreeSapling",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Wood",
        .resource_yield = 2,
        .renewable = true,
    },
    {
        .id = TILE_BUSH,
        .name = "Bush",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Fiber",
        .resource_yield = 3,
        .renewable = true,
    },
    {
        .id = TILE_BERRYBUSH,
        .name = "BerryBush",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Berries",
        .resource_yield = 3,
        .renewable = true,
    },
    {
        .id = TILE_FLOWERPATCH,
        .name = "FlowerPatch",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_TALLWEEDS,
        .name = "TallWeeds",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_VINEPATCH,
        .name = "VinePatch",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_VINES,
        .name = "Vines",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_MUSHROOMPATCH,
        .name = "MushroomPatch",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Mushrooms",
        .resource_yield = 3,
        .renewable = true,
    },
    {
        .id = TILE_GIANTMUSHROOM,
        .name = "GiantMushroom",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Mushrooms",
        .resource_yield = 6,
        .renewable = true,
    },
    {
        .id = TILE_CACTUS,
        .name = "Cactus",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "PlantFiber",
        .resource_yield = 4,
        .renewable = true,
    },
    {
        .id = TILE_DESERT_SHRUB,
        .name = "Desert Shrub",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Twigs",
        .resource_yield = 2,
        .renewable = true,
    },
    {
        .id = TILE_BOULDER,
        .name = "Boulder",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Stone",
        .resource_yield = 7,
        .renewable = false,
    },
    {
        .id = TILE_ROCKCLUSTER,
        .name = "RockCluster",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Stone",
        .resource_yield = 5,
        .renewable = false,
    },
    {
        .id = TILE_LARGEROCK,
        .name = "LargeRock",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Stone",
        .resource_yield = 10,
        .renewable = false,
    },
    {
        .id = TILE_CAVEENTRANCE,
        .name = "CaveEntrance",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
        .primary_resource = "Ore",
        .resource_yield = 8,
        .renewable = false,
    },
    {
        .id = TILE_WOODFOUNDATION,
        .name = "WoodFoundation",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_STONEFOUNDATION,
        .name = "StoneFoundation",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_CONCRETEFOUNDATION,
        .name = "ConcreteFoundation",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_BRICKFOUNDATION,
        .name = "BrickFoundation",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_STEELFOUNDATION,
        .name = "SteelFoundation",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_REINFORCEDFOUNDATION,
        .name = "ReinforcedFoundation",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_PIER,
        .name = "Pier",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_CARPET,
        .name = "Carpet",
        .walkable = true,
        .layer = TILE_LAYER_FLOOR,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_LOGWALL,
        .name = "LogWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_PLANKWALL,
        .name = "PlankWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_STONEWALL,
        .name = "StoneWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_BRICKWALL,
        .name = "BrickWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_CONCRETEWALL,
        .name = "ConcreteWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_REINFORCEDWALL,
        .name = "ReinforcedWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_STEELWALL,
        .name = "SteelWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_GLASSWALL,
        .name = "GlassWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_METALWALL,
        .name = "MetalWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_FENCEWOOD,
        .name = "FenceWood",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_FENCEMETAL,
        .name = "FenceMetal",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_FENCESTONE,
        .name = "FenceStone",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_FENCECHAIN,
        .name = "FenceChain",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_FENCEBARBED,
        .name = "FenceBarbed",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_BARRICADEWOOD,
        .name = "BarricadeWood",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_BARRICADESANDBAG,
        .name = "BarricadeSandbag",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_RUINEDWALL,
        .name = "RuinedWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_CRACKEDWALL,
        .name = "CrackedWall",
        .walkable = false,
        .layer = TILE_LAYER_STRUCTURE,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = true,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_TABLE,
        .name = "Table",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_TABLEROUND,
        .name = "TableRound",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_TABLELONG,
        .name = "TableLong",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_CHAIRWOOD,
        .name = "ChairWood",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_CHAIRMETAL,
        .name = "ChairMetal",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_SOFA,
        .name = "Sofa",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_BED,
        .name = "Bed",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_BUNKBED,
        .name = "BunkBed",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_CABINET,
        .name = "Cabinet",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_SHELF,
        .name = "Shelf",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_BOOKSHELF,
        .name = "Bookshelf",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_CHEST,
        .name = "Chest",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_LOCKER,
        .name = "Locker",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_DESK,
        .name = "Desk",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_OFFICEDESK,
        .name = "OfficeDesk",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_LAMP,
        .name = "Lamp",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_CEILINGLIGHT,
        .name = "CeilingLight",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_FLOORLAMP,
        .name = "FloorLamp",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_STOVE,
        .name = "Stove",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_OVEN,
        .name = "Oven",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_SINK,
        .name = "Sink",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_BATHTUB,
        .name = "Bathtub",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_TOILET,
        .name = "Toilet",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_SHOWER,
        .name = "Shower",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_FRIDGE,
        .name = "Fridge",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_WASHINGMACHINE,
        .name = "WashingMachine",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_DRYER,
        .name = "Dryer",
        .walkable = false,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = true,
        .blocks_swimming = true,
        .buildable_on = false,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 0,
    },
    {
        .id = TILE_SMALLAXE,
        .name = "SmallAxe",
        .walkable = true,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_PICKAXE,
        .name = "Pickaxe",
        .walkable = true,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_READER,
        .name = "Reader",
        .walkable = true,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_RADIO,
        .name = "Radio",
        .walkable = true,
        .layer = TILE_LAYER_OBJECT,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
    },
    {
        .id = TILE_SHIPPIECE,
        .name = "Ship Piece",
        .walkable = true,
        .layer = TILE_LAYER_GROUND,
        .blocks_land_movement = false,
        .blocks_swimming = true,
        .buildable_on = true,
        .requires_foundation = false,
        .is_liquid = false,
        .movement_cost_land = 1,
        .primary_resource = "ScrapMetal",
        .resource_yield = 6,
        .renewable = false,
    },
};

size_t tiles_count(void)
{
    return TILE_ID_COUNT;
}

const TileDefinition *tiles_get_definition(TileId id)
{
    if (id < 0 || id >= TILE_ID_COUNT)
    {
        return NULL;
    }

    return &g_tile_definitions[id];
}

TileId tiles_find_by_name(const char *name)
{
    if (name == NULL)
    {
        return TILE_ID_COUNT;
    }

    for (int i = 0; i < TILE_ID_COUNT; i++)
    {
        if (strcmp(g_tile_definitions[i].name, name) == 0)
        {
            return (TileId)i;
        }
    }

    return TILE_ID_COUNT;
}

const char *tiles_layer_name(TileLayer layer)
{
    switch (layer)
    {
    case TILE_LAYER_GROUND:
        return "ground";
    case TILE_LAYER_FLOOR:
        return "floor";
    case TILE_LAYER_OBJECT:
        return "object";
    case TILE_LAYER_STRUCTURE:
        return "structure";
    case TILE_LAYER_UNKNOWN:
    case TILE_LAYER_COUNT:
    default:
        return "unknown";
    }
}
